version: '3.9'

services:
  djangostock:
    build:
      context: .
    container_name: backend
    network_mode: host
    restart: unless-stopped
    command: >
      sh -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver
            "

